TFS_ArtillerySettings {
 m_iCooldownSeconds 60
 m_fInitialMissionDelaySeconds 2
 m_fBarrageDelaySeconds 20
 m_fShotCueDelaySeconds 3.75
 m_fSplashLeadSeconds 12
 m_fRadioInterCueDelaySeconds 1.25
 m_fAlertToneToDangerCloseDelaySeconds 1.25
 m_fDangerCloseToClearAreaDelaySeconds 1.25
 m_fMarkerPostImpactLifetimeSeconds 0
 m_bEnableRadioCues 1
 m_bPlayRadioCueSound 1
 m_bShowImpactMarker 1
 m_fDangerCloseRadiusMeters 300
 m_bEnableDistantFireSound 1
 m_fDistantFireOffsetMeters 2500
 m_iAudioRangeProfile 1
}
